version: "3.1"
services:
  # postgres service, you can comment it if you aleardy have a postgress instance to connect
  pgsql:
    container_name: pgsql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "root_password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "sparow"
    ports:
      - 5432:5432
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    networks:
      - sparow-core
  # main service of sparow
  core:
    container_name: core
    build: ./core
    restart: always
    volumes:
      - ./core:/var/www/html
      - /var/www/html/vendor
    ports:
      - 5000:80
    networks:
      - sparow-core
    depends_on:
      - pgsql
  # public web app
  public-webapp:
    container_name: public-webapp
    build: ./public-webapp
    restart: always
    volumes:
      - ./public-webapp:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5001:3000
    networks:
      - sparow-core
    stdin_open: true

networks:
  sparow-core:
    external: false
